### ISSUE TITLE
Look into a COCKLE_SETTINGS error in Cockle-Rake

### ISSUE THREAD

**Issue by cheapjack** [mcqn/cocklecraft-of-things#13]
Tried to follow cockle-rake instructions and keep getting

  File "cockle-rake.py", line 12, in <module>
    app.config.from_envvar('COCKLE_SETTINGS')
  File "/home/pi/cocklecraft-of-things/CockleRake/CockleRake/local/lib/python2.7/site-packages/flask/config.py", line 107, in from_envvar
    variable_name)
RuntimeError: The environment variable 'COCKLE_SETTINGS' is not set and as such configuration could not be loaded.  Set this variable and make it point to a configuration file

Have I just not made a config file somewhere?

**Comment by amcewen** [comment]
It was a step I'd missed out of the INSTALL.md instructions, sorry.  Have updated it now, but basically you need to export the COCKLE_SETTINGS environment variable to point to location of the settings.cfg file.
