### ISSUE TITLE
Look into a scope error in MinecraftTempSender

### ISSUE THREAD

**Issue by cheapjack** [mcqn/cocklecraft-of-things#14]
Arduino: 1.6.8 (Mac OS X), Board: "SparkFun ESP8266 Thing, 80 MHz, Serial, 115200"

cocklecraft-of-things/MinecraftTempSender/MinecraftTempSender.ino: In function 'void loop()':
MinecraftTempSender:113: error: 'mapFloat' was not declared in this scope
         float midPoint = mapFloat(constrainedTemp, kMinTemp, kMaxTemp, kFromY, kToY);
                                                                                    ^
exit status 1
'mapFloat' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by amcewen** [comment]
Weird.  mapFloat should be defined at the bottom of that file - line 194 on the version checked in at the minute :-/

Maybe give me a shout sometime when we're both in the same place and we can work out what the problem is.

**Comment by cheapjack** [comment]
we looked through the code and resolved this
