### ISSUE TITLE
Add a 4.7K Ohm pull-up resistor between the data pin and +V?

### ISSUE THREAD

**Issue by cheapjack** [mcqn/cocklecraft-of-things#15]
Pretty sure you need the resistor to get any sensible data...is the one in DoES working without? Well I only got it working with one, maybe is depends on the sensor

**Comment by amcewen** [comment]
I thought that was only needed if you were running it in "parasite power" mode when you only hook up the data and ground pins on the sensor?  The one in DoES has three connections - power, data, and ground.

That's my reading of the datasheet - http://datasheet.octopart.com/DS18B20%2B-Dallas-Semiconductor-datasheet-11984949.pdf (the start of page 3 talks about it), BICBW...
