### ISSUE TITLE
Push temperature data to cloud

### ISSUE THREAD

**Issue by amcewen** [mcqn/cocklecraft-of-things#5]
Push the data from issue #3 to somewhere else online other than a Minecraft server.  Could be opensensors.io or something that can run locally instead...

**Comment by cheapjack** [comment]
Im going to start a list of good places you could let data 'live' from the cockles
https://gitlab.com/cheapjack/cocklecraft-beach
Mainly cos wanted to remember how to use gitlab and liked idea of a flat beach metaphor where all kinds of cockles can live and not get stuck on any rocks ;) 
as a  list its got 2 things on it..

You got a list of other 'simple' 'good' and 'open' cloud type places? I always occasionally find some that look open/cheap/simple then forget about them and look from scratch and get confused. Like I thought platformio and opensensors.io where the same kind of thing

Sorry this is now a blog post not a comment. Or maybe a text adventure...
